/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Enums.CPUSuport;
import static Enums.CPUSuport.BMT;
import static Enums.CPUSuport.IMT;
import static Enums.CPUSuport.NONE;
import static Enums.CPUSuport.SMT;
import Interfaces.EstatisticasDelegate;
import javax.swing.JLabel;

/**
 *
 * @author Walla
 */
public class Estatisticas extends javax.swing.JPanel {
    
    EstatisticasDelegate delegate;
    boolean enableInit = false;
    
    /**
     * Creates new form Estatisticas
     * @param delegate ViewModel
     */
    public Estatisticas(EstatisticasDelegate delegate) {
        initComponents();
        this.delegate = delegate;
        
        suport_smt.setEnabled(delegate.getIsSuperScalar());
        estatisticas.setText(delegate.setInformations());
        markSuport();
        setButtons();
        
    }
  
    public final void markSuport(){
        switch(delegate.getSuport()){
            case NONE -> {
                suport_smt.setSelected(false);
                suport_imt.setSelected(false);
                suport_bmt.setSelected(false);
            }
            case IMT -> {
                suport_smt.setSelected(false);
                suport_imt.setSelected(true);
                suport_bmt.setSelected(false);
            }
            case BMT -> {
                suport_smt.setSelected(false);
                suport_imt.setSelected(false);
                suport_bmt.setSelected(true);
            }
            case SMT -> {
                suport_smt.setSelected(true);
                suport_imt.setSelected(false);
                suport_bmt.setSelected(false);
            }
        }
    }
    
    public final void setButtons(){
        if(!delegate.enableInitMode()) {
            iniciar_btn.setText("Importar Código");
            reiniciar_btn.setEnabled(false);
            enableInit = false;
        } else if(!delegate.isStart()){
            enableInit = true;
            iniciar_btn.setText("Iniciar");
            reiniciar_btn.setText("Reiniciar");
            reiniciar_btn.setEnabled(true);
        } else {
            iniciar_btn.setText("Próximo Ciclo");
            reiniciar_btn.setText("Reiniciar");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arquitetura_processador = new javax.swing.JComboBox<>();
        suport_imt = new javax.swing.JCheckBox();
        suport_bmt = new javax.swing.JCheckBox();
        suport_smt = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        estatisticas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        iniciar_btn = new javax.swing.JButton();
        reiniciar_btn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMinimumSize(new java.awt.Dimension(200, 420));
        setPreferredSize(new java.awt.Dimension(200, 420));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 8, 0, 8, 0};
        setLayout(layout);

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 60));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 8, 0, 8, 0};
        jPanel2Layout.rowHeights = new int[] {0, 8, 0, 8, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Definições");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Arquitetura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel3, gridBagConstraints);

        arquitetura_processador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escalar", "Super Escalar" }));
        arquitetura_processador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquitetura_processadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 100;
        jPanel2.add(arquitetura_processador, gridBagConstraints);

        suport_imt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        suport_imt.setText("Suporte IMT");
        suport_imt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suport_imtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(suport_imt, gridBagConstraints);

        suport_bmt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        suport_bmt.setText("Suporte BMT");
        suport_bmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suport_bmtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(suport_bmt, gridBagConstraints);

        suport_smt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        suport_smt.setText("Suporte SMT");
        suport_smt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suport_smtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel2.add(suport_smt, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jPanel2, gridBagConstraints);

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 250));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estatisticas");
        jPanel4.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(57, 46));
        jPanel1.setLayout(new java.awt.BorderLayout());

        estatisticas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        estatisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estatisticas.setToolTipText("");
        jPanel1.add(estatisticas, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(jPanel4, gridBagConstraints);

        jPanel3.setMinimumSize(new java.awt.Dimension(200, 27));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        iniciar_btn.setText("Iniciar");
        iniciar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 20;
        jPanel3.add(iniciar_btn, gridBagConstraints);

        reiniciar_btn.setText("Reiniciar");
        reiniciar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciar_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 20;
        jPanel3.add(reiniciar_btn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 250.0;
        gridBagConstraints.weighty = 80.0;
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void suport_imtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suport_imtActionPerformed
        delegate.setSuport(CPUSuport.IMT);
    }//GEN-LAST:event_suport_imtActionPerformed

    private void suport_bmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suport_bmtActionPerformed
        delegate.setSuport(CPUSuport.BMT);
    }//GEN-LAST:event_suport_bmtActionPerformed

    private void suport_smtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suport_smtActionPerformed
        delegate.setSuport(CPUSuport.SMT);
    }//GEN-LAST:event_suport_smtActionPerformed

    private void arquitetura_processadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquitetura_processadorActionPerformed
        boolean isSuperScalar = arquitetura_processador.getSelectedIndex() == 1;
        delegate.setCPUMode(isSuperScalar);
    }//GEN-LAST:event_arquitetura_processadorActionPerformed

    private void iniciar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar_btnActionPerformed
        if(enableInit){
            delegate.runCycle(false);
        } else {
            delegate.importCode();
        }
        estatisticas.setText(delegate.setInformations());
    }//GEN-LAST:event_iniciar_btnActionPerformed

    private void reiniciar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciar_btnActionPerformed
        if(enableInit){
            delegate.restart();
        }
    }//GEN-LAST:event_reiniciar_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> arquitetura_processador;
    private javax.swing.JLabel estatisticas;
    private javax.swing.JButton iniciar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton reiniciar_btn;
    private javax.swing.JCheckBox suport_bmt;
    private javax.swing.JCheckBox suport_imt;
    private javax.swing.JCheckBox suport_smt;
    // End of variables declaration//GEN-END:variables
   
    public void repaint(){
        if(delegate != null){
            suport_smt.setEnabled(delegate.getIsSuperScalar());
            markSuport();
            setButtons();
            super.repaint();
        }
    }
}
